import type { Subject, Chapter, TestQuestion, HistoryEntry } from './types'

export const SUBJECTS: Subject[] = [
  { id: 'math', name: 'Mathematics', emoji: '📐', color: '#4F46E5', bgColor: '#EEF2FF', chapters: 14, progress: 65 },
  { id: 'science', name: 'Science', emoji: '🔬', color: '#10B981', bgColor: '#ECFDF5', chapters: 12, progress: 42 },
  { id: 'english', name: 'English', emoji: '📖', color: '#F59E0B', bgColor: '#FFFBEB', chapters: 8, progress: 78 },
  { id: 'hindi', name: 'Hindi', emoji: '🔤', color: '#EF4444', bgColor: '#FEF2F2', chapters: 10, progress: 30 },
  { id: 'social', name: 'Social Science', emoji: '🌍', color: '#8B5CF6', bgColor: '#F5F3FF', chapters: 18, progress: 55 },
  { id: 'computer', name: 'Computer Science', emoji: '💻', color: '#06B6D4', bgColor: '#ECFEFF', chapters: 9, progress: 90 },
]

export const CHAPTERS_BY_SUBJECT: Record<string, Chapter[]> = {
  math: [
    { id: 'real-numbers', name: 'Real Numbers', questionCount: 45 },
    { id: 'polynomials', name: 'Polynomials', questionCount: 38 },
    { id: 'linear-eq', name: 'Pair of Linear Equations', questionCount: 52 },
    { id: 'quadratic-eq', name: 'Quadratic Equations', questionCount: 60 },
    { id: 'ap', name: 'Arithmetic Progressions', questionCount: 48 },
    { id: 'triangles', name: 'Triangles', questionCount: 55 },
    { id: 'coord-geo', name: 'Coordinate Geometry', questionCount: 40 },
    { id: 'trig', name: 'Introduction to Trigonometry', questionCount: 65 },
    { id: 'trig-apps', name: 'Applications of Trigonometry', questionCount: 30 },
    { id: 'circles', name: 'Circles', questionCount: 35 },
    { id: 'areas', name: 'Areas Related to Circles', questionCount: 42 },
    { id: 'surface', name: 'Surface Areas and Volumes', questionCount: 58 },
    { id: 'statistics', name: 'Statistics', questionCount: 50 },
    { id: 'probability', name: 'Probability', questionCount: 44 },
  ],
  science: [
    { id: 'chem-reactions', name: 'Chemical Reactions and Equations', questionCount: 55 },
    { id: 'acids-bases', name: 'Acids, Bases and Salts', questionCount: 48 },
    { id: 'metals', name: 'Metals and Non-metals', questionCount: 60 },
    { id: 'carbon', name: 'Carbon and its Compounds', questionCount: 52 },
    { id: 'life-processes', name: 'Life Processes', questionCount: 65 },
    { id: 'control', name: 'Control and Coordination', questionCount: 45 },
    { id: 'reproduction', name: 'How do Organisms Reproduce?', questionCount: 50 },
    { id: 'heredity', name: 'Heredity and Evolution', questionCount: 42 },
    { id: 'light', name: 'Light: Reflection and Refraction', questionCount: 70 },
    { id: 'human-eye', name: 'Human Eye and Colourful World', questionCount: 38 },
    { id: 'electricity', name: 'Electricity', questionCount: 75 },
    { id: 'magnetic', name: 'Magnetic Effects of Electric Current', questionCount: 60 },
  ],
  english: [
    { id: 'prose', name: 'First Flight — Prose', questionCount: 40 },
    { id: 'poetry', name: 'First Flight — Poetry', questionCount: 30 },
    { id: 'footprints', name: 'Footprints Without Feet', questionCount: 35 },
    { id: 'grammar', name: 'Grammar & Writing', questionCount: 80 },
    { id: 'comprehension', name: 'Reading Comprehension', questionCount: 60 },
    { id: 'letter', name: 'Letter & Application Writing', questionCount: 25 },
    { id: 'essay', name: 'Essay & Paragraph Writing', questionCount: 20 },
    { id: 'notice', name: 'Notice & Poster Writing', questionCount: 18 },
  ],
  hindi: [
    { id: 'kshitij', name: 'क्षितिज — गद्य', questionCount: 45 },
    { id: 'kshitij-kavya', name: 'क्षितिज — काव्य', questionCount: 38 },
    { id: 'kritika', name: 'कृतिका', questionCount: 32 },
    { id: 'vyakaran', name: 'व्याकरण', questionCount: 90 },
    { id: 'lekhan', name: 'लेखन कौशल', questionCount: 40 },
    { id: 'apathit', name: 'अपठित गद्यांश', questionCount: 55 },
    { id: 'patra', name: 'पत्र लेखन', questionCount: 25 },
    { id: 'anuched', name: 'अनुच्छेद लेखन', questionCount: 20 },
    { id: 'sanchayan', name: 'संचयन', questionCount: 28 },
    { id: 'kahani', name: 'कहानी लेखन', questionCount: 18 },
  ],
  social: [
    { id: 'nationalism', name: 'Nationalism in India', questionCount: 55 },
    { id: 'indo-china', name: 'The Rise of Nationalism in Europe', questionCount: 48 },
    { id: 'resources', name: 'Resources and Development', questionCount: 52 },
    { id: 'water', name: 'Water Resources', questionCount: 40 },
    { id: 'agriculture', name: 'Agriculture', questionCount: 45 },
    { id: 'minerals', name: 'Minerals and Energy Resources', questionCount: 50 },
    { id: 'manufacturing', name: 'Manufacturing Industries', questionCount: 55 },
    { id: 'development', name: 'Development', questionCount: 42 },
    { id: 'sectors', name: 'Sectors of Indian Economy', questionCount: 48 },
    { id: 'money', name: 'Money and Credit', questionCount: 38 },
    { id: 'globalisation', name: 'Globalisation and Indian Economy', questionCount: 45 },
    { id: 'democracy', name: 'Power Sharing', questionCount: 50 },
    { id: 'federalism', name: 'Federalism', questionCount: 55 },
    { id: 'gender', name: 'Gender, Religion and Caste', questionCount: 42 },
    { id: 'political-parties', name: 'Political Parties', questionCount: 48 },
    { id: 'outcomes', name: 'Outcomes of Democracy', questionCount: 35 },
    { id: 'challenges', name: 'Challenges to Democracy', questionCount: 38 },
    { id: 'print', name: 'Print Culture and the Modern World', questionCount: 42 },
  ],
  computer: [
    { id: 'networking', name: 'Networking Concepts', questionCount: 55 },
    { id: 'python-intro', name: 'Introduction to Python', questionCount: 70 },
    { id: 'data-types', name: 'Data Types and Variables', questionCount: 60 },
    { id: 'control-flow', name: 'Control Flow Statements', questionCount: 65 },
    { id: 'functions', name: 'Functions and Modules', questionCount: 55 },
    { id: 'strings', name: 'Strings and List Manipulation', questionCount: 68 },
    { id: 'file-handling', name: 'File Handling', questionCount: 45 },
    { id: 'sql', name: 'SQL and Databases', questionCount: 72 },
    { id: 'cyber-security', name: 'Cyber Safety & Ethics', questionCount: 40 },
  ],
}

export const SAMPLE_QUESTIONS: TestQuestion[] = [
  {
    id: 1,
    question: 'If the HCF of 65 and 117 is expressible in the form 65m – 117, then the value of m is',
    options: ['1', '2', '3', '4'],
    correctIndex: 1,
    explanation: 'HCF(65, 117) = 13. Given 65m – 117 = 13 → 65m = 130 → m = 2.',
    chapter: 'Real Numbers',
  },
  {
    id: 2,
    question: 'The zeroes of the polynomial x² – 3x – 4 are',
    options: ['1 and –4', '–1 and 4', '2 and –2', '4 and 4'],
    correctIndex: 1,
    explanation: 'x² – 3x – 4 = (x – 4)(x + 1) = 0, giving x = 4 or x = –1.',
    chapter: 'Polynomials',
  },
  {
    id: 3,
    question: 'For what value of k do 2x + 3y = 5 and 4x + ky = 10 have infinitely many solutions?',
    options: ['3', '4', '6', '8'],
    correctIndex: 2,
    explanation: 'For infinitely many solutions: 2/4 = 3/k = 5/10 → k = 6.',
    chapter: 'Pair of Linear Equations',
  },
  {
    id: 4,
    question: 'Which of the following is a quadratic equation?',
    options: ['x³ + 2x + 1 = 0', 'x² + 1/x = 2', '(x+1)(x-2) = x²', '2x² + 3x = x² + 5'],
    correctIndex: 3,
    explanation: '2x² + 3x = x² + 5 simplifies to x² + 3x – 5 = 0, which is a standard quadratic.',
    chapter: 'Quadratic Equations',
  },
  {
    id: 5,
    question: 'The 10th term of the AP: 5, 8, 11, 14, … is',
    options: ['32', '35', '38', '41'],
    correctIndex: 0,
    explanation: 'a = 5, d = 3. a₁₀ = 5 + 9 × 3 = 5 + 27 = 32.',
    chapter: 'Arithmetic Progressions',
  },
  {
    id: 6,
    question: 'In △ABC, if AB² = BC² + CA², the right angle is at',
    options: ['A', 'B', 'C', 'Cannot be determined'],
    correctIndex: 2,
    explanation: 'By Pythagoras theorem, the right angle is opposite to AB, which is angle C.',
    chapter: 'Triangles',
  },
  {
    id: 7,
    question: 'The distance between (3, 4) and (–3, –4) is',
    options: ['5', '7', '10', '14'],
    correctIndex: 2,
    explanation: 'd = √[(3+3)² + (4+4)²] = √[36+64] = √100 = 10.',
    chapter: 'Coordinate Geometry',
  },
  {
    id: 8,
    question: 'sin 30° × cos 60° + cos 30° × sin 60° equals',
    options: ['0', '1/2', '√3/2', '1'],
    correctIndex: 3,
    explanation: 'This equals sin(30°+60°) = sin 90° = 1 by the sine addition formula.',
    chapter: 'Introduction to Trigonometry',
  },
  {
    id: 9,
    question: "If shadow length is √3 times the tower's height, the angle of elevation of the sun is",
    options: ['30°', '45°', '60°', '90°'],
    correctIndex: 0,
    explanation: 'tan θ = h/(√3h) = 1/√3 → θ = 30°.',
    chapter: 'Applications of Trigonometry',
  },
  {
    id: 10,
    question: 'Area of a sector with radius 7 cm and central angle 90° is',
    options: ['11 cm²', '38.5 cm²', '77 cm²', '154 cm²'],
    correctIndex: 1,
    explanation: 'Area = (90/360) × (22/7) × 49 = ¼ × 154 = 38.5 cm².',
    chapter: 'Areas Related to Circles',
  },
  {
    id: 11,
    question: 'The chemical formula of rust is',
    options: ['Fe₂O₃', 'Fe₃O₄', 'Fe₂O₃·xH₂O', 'FeO'],
    correctIndex: 2,
    explanation: 'Rust is hydrated iron(III) oxide with formula Fe₂O₃·xH₂O, formed by oxidation of iron in the presence of water.',
    chapter: 'Chemical Reactions and Equations',
  },
  {
    id: 12,
    question: 'Which of the following is an amphoteric oxide?',
    options: ['Na₂O', 'SO₂', 'Al₂O₃', 'CaO'],
    correctIndex: 2,
    explanation: 'Al₂O₃ reacts with both acids and bases (amphoteric). Na₂O and CaO are basic; SO₂ is acidic.',
    chapter: 'Acids, Bases and Salts',
  },
  {
    id: 13,
    question: 'The process of depositing a layer of zinc on iron is called',
    options: ['Tinning', 'Galvanisation', 'Electroplating', 'Alloying'],
    correctIndex: 1,
    explanation: 'Galvanisation is the process of coating iron with zinc to prevent corrosion.',
    chapter: 'Metals and Non-metals',
  },
  {
    id: 14,
    question: 'A homologous series is characterised by',
    options: ['Same molecular formula', 'Same functional group', 'Same physical properties', 'Same empirical formula'],
    correctIndex: 1,
    explanation: 'Members of a homologous series share the same functional group, differ by –CH₂–, and show a gradation in properties.',
    chapter: 'Carbon and its Compounds',
  },
  {
    id: 15,
    question: 'The site of photosynthesis in the chloroplast is',
    options: ['Stroma', 'Thylakoid membrane', 'Outer membrane', 'Inner membrane'],
    correctIndex: 1,
    explanation: 'The light reactions of photosynthesis occur on the thylakoid membranes where chlorophyll absorbs light energy.',
    chapter: 'Life Processes',
  },
]

export const MOCK_HISTORY: HistoryEntry[] = [
  {
    id: '1',
    subject: 'Mathematics',
    subjectColor: '#4F46E5',
    chapters: ['Real Numbers', 'Polynomials'],
    score: 34,
    total: 40,
    date: new Date(Date.now() - 86400000 * 2),
    timeTaken: 1800,
  },
  {
    id: '2',
    subject: 'Science',
    subjectColor: '#10B981',
    chapters: ['Chemical Reactions and Equations'],
    score: 18,
    total: 25,
    date: new Date(Date.now() - 86400000 * 5),
    timeTaken: 1200,
  },
  {
    id: '3',
    subject: 'Mathematics',
    subjectColor: '#4F46E5',
    chapters: ['Quadratic Equations', 'Arithmetic Progressions'],
    score: 22,
    total: 50,
    date: new Date(Date.now() - 86400000 * 7),
    timeTaken: 2400,
  },
  {
    id: '4',
    subject: 'English',
    subjectColor: '#F59E0B',
    chapters: ['Grammar & Writing', 'Reading Comprehension'],
    score: 40,
    total: 40,
    date: new Date(Date.now() - 86400000 * 10),
    timeTaken: 1500,
  },
  {
    id: '5',
    subject: 'Computer Science',
    subjectColor: '#06B6D4',
    chapters: ['Introduction to Python', 'Data Types and Variables'],
    score: 28,
    total: 30,
    date: new Date(Date.now() - 86400000 * 14),
    timeTaken: 1080,
  },
]

export const AI_RESPONSES: Record<string, string> = {
  default:
    "That's a great question! This topic is an important part of your CBSE syllabus. Let me break it down clearly so you understand both the concept and how to apply it in exams. Would you like a worked example?",
  formula:
    "Here's the key formula you need:\n\nFor this type of problem, identify the given values, choose the right formula, substitute carefully, and simplify step by step. Always check your units at the end!",
  example:
    "Let me solve a step-by-step example:\n\nStep 1: Read and understand what's given.\nStep 2: Identify what needs to be found.\nStep 3: Choose the appropriate method.\nStep 4: Solve carefully and verify your answer.",
  exam: "For board exams, focus on:\n• NCERT exercises (all solved + unsolved)\n• Previous 10 years question papers\n• Important derivations and proofs\n• Common mistakes to avoid\n\nShall I create a mini quiz to test you?",
}

export function getAIResponse(msg: string): string {
  const l = msg.toLowerCase()
  if (l.includes('formula') || l.includes('equation')) return AI_RESPONSES.formula
  if (l.includes('example') || l.includes('solve') || l.includes('how')) return AI_RESPONSES.example
  if (l.includes('exam') || l.includes('board') || l.includes('marks')) return AI_RESPONSES.exam
  return AI_RESPONSES.default
}
